name: Check Format Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/workflow-actions/setup

      - name: Run ruff for format checking
        run: |
          make format-check

      - name: Cleanup Environment
        uses: ./.github/workflow-actions/cleanup
