name: Test Coverage Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MATI Environment
        uses: ./.github/workflow-actions/setup-mati

      - name: Run coverage tests
        run: |
          make test-coverage

    #   - name: Upload coverage report
    #     if: always()
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: coverage-report
    #       path: htmlcov/
    #       retention-days: 30

      - name: Cleanup MATI Environment
        uses: ./.github/workflow-actions/cleanup-mati
