name: Test Examples Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MATI Environment
        uses: ./.github/workflow-actions/setup-mati

      - name: Run example tests
        run: |
          make test-examples

      - name: Cleanup MATI Environment
        uses: ./.github/workflow-actions/cleanup-mati
