name: Test Requirements Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/workflow-actions/setup

      - name: Run requirements tests
        run: |
          make test-requirements

      - name: Cleanup Environment
        uses: ./.github/workflow-actions/cleanup
